version: "3.8"
services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password
      POSTGRES_DB: db-todo
    ports:
      - 80:3000
    depends_on:
      - db
    secrets:
      - db-password
    networks:
      - network-todo
  db:
    image: postgres:13
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-todo-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db-todo
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - 5432:5432
    networks:
      - network-todo
volumes:
  db-todo-data:
secrets:
  db-password:
    file: db/password.txt
networks:
  network-todo:
    driver: bridge

